site_name: BalatroBot
site_description: A bot framework for Balatro
site_author: 'S1M0N38'
repo_name: 'S1M0N38/balatrobot'
repo_url: https://github.com/S1M0N38/balatrobot
site_url: https://s1m0n38.github.io/balatrobot/
docs_dir: docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: black
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: white
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
nav:
  - index.md
  - Installation: installation.md
  - Bot Development: bot-development.md
  - API Protocol: api-protocol.md
  - Troubleshooting: troubleshooting.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
