site_name: BalatroBot
site_description: A bot framework for Balatro
site_author: 'S1M0N38'
repo_name: 'S1M0N38/balatrobot'
repo_url: https://github.com/S1M0N38/balatrobot
site_url: https://s1m0n38.github.io/balatrobot/
docs_dir: docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: black
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      accent: white
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
plugins:
  - search
  - llmstxt:
      markdown_description: |
        BalatroBot is a Python framework for developing automated bots to play the card game Balatro.
        The architecture consists of three main layers: a communication layer using TCP protocol with Lua API,
        a Python framework layer for bot development, and comprehensive testing and documentation systems.
        The project enables real-time bidirectional communication between the game and bot through TCP sockets.
      sections:
        Documentation:
          - index.md
          - installation.md
          - developing-bots.md
          - balatrobot-api.md
          - protocol-api.md
      full_output: llms-full.txt
      autoclean: false
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false
            show_bases: false
            filters: ["!^_"]
            heading_level: 4
nav:
  - index.md
  - Installation: installation.md
  - Developing Bots: developing-bots.md
  - BalatroBot API: balatrobot-api.md
  - Protocol API: protocol-api.md
  - Troubleshooting: troubleshooting.md
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
