site_name: BalatroBot
site_description: A bot framework for Balatro
site_author: 'S1M0N38'
repo_name: 'S1M0N38/balatrobot'
repo_url: https://github.com/S1M0N38/balatrobot
docs_dir: docs/

theme:
  name: material

nav:
  - Home: README.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Architecture: architecture.md
  - Bot Development: bot-development.md
  - Python API: python-api.md
  - Examples: examples.md
  - Troubleshooting: troubleshooting.md